CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id VARCHAR(50) NOT NULL,
    password_hash VARCHAR(100) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uq_users_account_id UNIQUE (account_id)
);

CREATE TABLE stores (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    time_zone VARCHAR(50) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE user_store_memberships (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    store_id BIGINT NOT NULL,
    role VARCHAR(20) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_memberships_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_memberships_store FOREIGN KEY (store_id) REFERENCES stores (id) ON DELETE CASCADE,
    CONSTRAINT uq_memberships_user_store UNIQUE (user_id, store_id),
    CONSTRAINT ck_memberships_role CHECK (role IN ('OWNER', 'MANAGER'))
);

CREATE INDEX idx_memberships_store_user
    ON user_store_memberships (store_id, user_id);

CREATE TABLE products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    store_id BIGINT NOT NULL,
    name VARCHAR(100) NOT NULL,
    price BIGINT NOT NULL,
    active BOOLEAN NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_products_store FOREIGN KEY (store_id) REFERENCES stores (id) ON DELETE CASCADE,
    CONSTRAINT ck_products_price CHECK (price >= 0)
);

CREATE INDEX idx_products_store_active
    ON products (store_id, active);

CREATE TABLE sales (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    store_id BIGINT NOT NULL,
    transaction_id VARCHAR(100) NOT NULL,
    line_no INTEGER NOT NULL,
    product_id BIGINT NOT NULL,
    product_name_snapshot VARCHAR(100) NOT NULL,
    product_price_snapshot BIGINT NOT NULL,
    quantity INTEGER NOT NULL,
    paid_amount BIGINT NOT NULL,
    sold_at TIMESTAMP WITH TIME ZONE NOT NULL,
    status VARCHAR(20) NOT NULL,
    cancelled_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_sales_store FOREIGN KEY (store_id) REFERENCES stores (id) ON DELETE CASCADE,
    CONSTRAINT fk_sales_product FOREIGN KEY (product_id) REFERENCES products (id),
    CONSTRAINT uq_sales_store_transaction_line UNIQUE (store_id, transaction_id, line_no),
    CONSTRAINT ck_sales_line_no CHECK (line_no > 0),
    CONSTRAINT ck_sales_product_price CHECK (product_price_snapshot >= 0),
    CONSTRAINT ck_sales_quantity CHECK (quantity > 0),
    CONSTRAINT ck_sales_paid_amount CHECK (paid_amount >= 0),
    CONSTRAINT ck_sales_status CHECK (status IN ('COMPLETED', 'CANCELLED')),
    CONSTRAINT ck_sales_cancelled_at CHECK (
        (status = 'COMPLETED' AND cancelled_at IS NULL)
        OR (status = 'CANCELLED' AND cancelled_at IS NOT NULL)
    )
);

CREATE INDEX idx_sales_store_sold_at
    ON sales (store_id, sold_at);

CREATE INDEX idx_sales_store_transaction
    ON sales (store_id, transaction_id);

CREATE TABLE hourly_visitor_counts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    store_id BIGINT NOT NULL,
    business_date DATE NOT NULL,
    hour INTEGER NOT NULL,
    visitor_count BIGINT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_hourly_visitors_store FOREIGN KEY (store_id) REFERENCES stores (id) ON DELETE CASCADE,
    CONSTRAINT uq_hourly_visitors_store_date_hour UNIQUE (store_id, business_date, hour),
    CONSTRAINT ck_hourly_visitors_hour CHECK (hour BETWEEN 0 AND 23),
    CONSTRAINT ck_hourly_visitors_count CHECK (visitor_count >= 0)
);

CREATE INDEX idx_hourly_visitors_store_date
    ON hourly_visitor_counts (store_id, business_date);
