CREATE TABLE sale_transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    store_id BIGINT NOT NULL,
    client_transaction_id VARCHAR(100),
    sold_at TIMESTAMP WITH TIME ZONE NOT NULL,
    status VARCHAR(20) NOT NULL,
    cancelled_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_sale_transactions_store
        FOREIGN KEY (store_id) REFERENCES stores (id) ON DELETE CASCADE,
    CONSTRAINT uq_sale_transactions_store_client_id
        UNIQUE (store_id, client_transaction_id),
    CONSTRAINT ck_sale_transactions_status
        CHECK (status IN ('COMPLETED', 'CANCELLED')),
    CONSTRAINT ck_sale_transactions_cancelled_at CHECK (
        (status = 'COMPLETED' AND cancelled_at IS NULL)
        OR (status = 'CANCELLED' AND cancelled_at IS NOT NULL)
    )
);

CREATE INDEX idx_sale_transactions_store_sold_at
    ON sale_transactions (store_id, sold_at);

CREATE TABLE sale_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sale_transaction_id BIGINT NOT NULL,
    line_no INTEGER NOT NULL,
    product_id BIGINT NOT NULL,
    product_name_snapshot VARCHAR(100) NOT NULL,
    product_price_snapshot BIGINT NOT NULL,
    quantity INTEGER NOT NULL,
    paid_amount BIGINT NOT NULL,
    CONSTRAINT fk_sale_items_transaction
        FOREIGN KEY (sale_transaction_id) REFERENCES sale_transactions (id) ON DELETE CASCADE,
    CONSTRAINT fk_sale_items_product
        FOREIGN KEY (product_id) REFERENCES products (id),
    CONSTRAINT uq_sale_items_transaction_line
        UNIQUE (sale_transaction_id, line_no),
    CONSTRAINT ck_sale_items_line_no CHECK (line_no > 0),
    CONSTRAINT ck_sale_items_product_price CHECK (product_price_snapshot >= 0),
    CONSTRAINT ck_sale_items_quantity CHECK (quantity > 0),
    CONSTRAINT ck_sale_items_paid_amount CHECK (paid_amount >= 0)
);

CREATE INDEX idx_sale_items_transaction
    ON sale_items (sale_transaction_id);

CREATE TABLE sale_migration_validation (
    store_id BIGINT NOT NULL,
    transaction_id VARCHAR(100) NOT NULL,
    sold_at_variants BIGINT NOT NULL,
    status_variants BIGINT NOT NULL,
    CONSTRAINT ck_sale_migration_single_sold_at CHECK (sold_at_variants = 1),
    CONSTRAINT ck_sale_migration_single_status CHECK (status_variants = 1)
);

INSERT INTO sale_migration_validation (
    store_id,
    transaction_id,
    sold_at_variants,
    status_variants
)
SELECT
    store_id,
    transaction_id,
    COUNT(DISTINCT sold_at),
    COUNT(DISTINCT status)
FROM sales
GROUP BY store_id, transaction_id;

DROP TABLE sale_migration_validation;

INSERT INTO sale_transactions (
    store_id,
    client_transaction_id,
    sold_at,
    status,
    cancelled_at,
    created_at
)
SELECT
    store_id,
    transaction_id,
    MIN(sold_at),
    CASE
        WHEN SUM(CASE WHEN status = 'COMPLETED' THEN 1 ELSE 0 END) = 0
            THEN 'CANCELLED'
        ELSE 'COMPLETED'
    END,
    CASE
        WHEN SUM(CASE WHEN status = 'COMPLETED' THEN 1 ELSE 0 END) = 0
            THEN MAX(cancelled_at)
        ELSE NULL
    END,
    MIN(created_at)
FROM sales
GROUP BY store_id, transaction_id;

INSERT INTO sale_items (
    sale_transaction_id,
    line_no,
    product_id,
    product_name_snapshot,
    product_price_snapshot,
    quantity,
    paid_amount
)
SELECT
    sale_transactions.id,
    sales.line_no,
    sales.product_id,
    sales.product_name_snapshot,
    sales.product_price_snapshot,
    sales.quantity,
    sales.paid_amount
FROM sales
JOIN sale_transactions
    ON sale_transactions.store_id = sales.store_id
    AND sale_transactions.client_transaction_id = sales.transaction_id;

DROP TABLE sales;
DROP TABLE hourly_visitor_counts;
