ALTER TABLE users
    ADD COLUMN name VARCHAR(100);

ALTER TABLE users
    ADD COLUMN email VARCHAR(255);

ALTER TABLE users
    ADD CONSTRAINT uq_users_email UNIQUE (email);

ALTER TABLE stores
    ADD COLUMN closing_time TIME NOT NULL DEFAULT '22:00:00';

CREATE TABLE consultings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    store_id BIGINT NOT NULL,
    target_date DATE NOT NULL,
    title VARCHAR(200),
    content TEXT,
    status VARCHAR(20) NOT NULL,
    attempt_count INTEGER NOT NULL DEFAULT 0,
    next_retry_at TIMESTAMP WITH TIME ZONE,
    last_error VARCHAR(1000),
    generated_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_consultings_store FOREIGN KEY (store_id) REFERENCES stores (id) ON DELETE CASCADE,
    CONSTRAINT uq_consultings_store_target_date UNIQUE (store_id, target_date),
    CONSTRAINT ck_consultings_status CHECK (status IN ('PENDING', 'COMPLETED', 'FAILED')),
    CONSTRAINT ck_consultings_attempt_count CHECK (attempt_count >= 0)
);

CREATE INDEX idx_consultings_store_created
    ON consultings (store_id, created_at);

CREATE INDEX idx_consultings_retry
    ON consultings (status, next_retry_at);

CREATE TABLE chat_rooms (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    store_id BIGINT NOT NULL,
    title VARCHAR(100) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_chat_rooms_store FOREIGN KEY (store_id) REFERENCES stores (id) ON DELETE CASCADE
);

CREATE INDEX idx_chat_rooms_store_updated
    ON chat_rooms (store_id, updated_at);

CREATE TABLE chat_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chat_room_id BIGINT NOT NULL,
    request_message_id BIGINT,
    client_message_id VARCHAR(100),
    role VARCHAR(20) NOT NULL,
    status VARCHAR(20) NOT NULL,
    content TEXT NOT NULL,
    retry_count INTEGER NOT NULL DEFAULT 0,
    next_retry_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_chat_messages_room FOREIGN KEY (chat_room_id) REFERENCES chat_rooms (id) ON DELETE CASCADE,
    CONSTRAINT fk_chat_messages_request FOREIGN KEY (request_message_id) REFERENCES chat_messages (id) ON DELETE CASCADE,
    CONSTRAINT uq_chat_messages_room_client_id UNIQUE (chat_room_id, client_message_id),
    CONSTRAINT ck_chat_messages_role CHECK (role IN ('USER', 'ASSISTANT')),
    CONSTRAINT ck_chat_messages_status CHECK (status IN ('PENDING', 'COMPLETED', 'FAILED')),
    CONSTRAINT ck_chat_messages_retry_count CHECK (retry_count >= 0)
);

CREATE INDEX idx_chat_messages_room_id
    ON chat_messages (chat_room_id, id);

CREATE INDEX idx_chat_messages_retry
    ON chat_messages (status, next_retry_at);

CREATE TABLE media_files (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    store_id BIGINT NOT NULL,
    public_id VARCHAR(36) NOT NULL,
    original_name VARCHAR(255) NOT NULL,
    storage_name VARCHAR(100) NOT NULL,
    content_type VARCHAR(50) NOT NULL,
    size_bytes BIGINT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_media_files_store FOREIGN KEY (store_id) REFERENCES stores (id) ON DELETE CASCADE,
    CONSTRAINT uq_media_files_public_id UNIQUE (public_id),
    CONSTRAINT uq_media_files_storage_name UNIQUE (storage_name),
    CONSTRAINT ck_media_files_size CHECK (size_bytes > 0)
);

CREATE INDEX idx_media_files_store_created
    ON media_files (store_id, created_at);

CREATE TABLE marketing_contents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    store_id BIGINT NOT NULL,
    title VARCHAR(150) NOT NULL,
    content TEXT NOT NULL,
    hashtags TEXT NOT NULL,
    status VARCHAR(20) NOT NULL,
    idempotency_key VARCHAR(100) NOT NULL,
    publish_attempt_count INTEGER NOT NULL DEFAULT 0,
    next_publish_at TIMESTAMP WITH TIME ZONE,
    approved_at TIMESTAMP WITH TIME ZONE,
    published_at TIMESTAMP WITH TIME ZONE,
    external_post_id VARCHAR(100),
    published_url VARCHAR(1000),
    failure_reason VARCHAR(1000),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_marketing_contents_store FOREIGN KEY (store_id) REFERENCES stores (id) ON DELETE CASCADE,
    CONSTRAINT uq_marketing_idempotency_key UNIQUE (idempotency_key),
    CONSTRAINT ck_marketing_status CHECK (status IN ('DRAFT', 'APPROVED', 'PUBLISHING', 'PUBLISHED', 'FAILED')),
    CONSTRAINT ck_marketing_publish_attempt_count CHECK (publish_attempt_count >= 0)
);

CREATE INDEX idx_marketing_store_created
    ON marketing_contents (store_id, created_at);

CREATE INDEX idx_marketing_publish_retry
    ON marketing_contents (status, next_publish_at);

CREATE TABLE marketing_media (
    marketing_id BIGINT NOT NULL,
    media_id BIGINT NOT NULL,
    position INTEGER NOT NULL,
    CONSTRAINT pk_marketing_media PRIMARY KEY (marketing_id, media_id),
    CONSTRAINT uq_marketing_media_position UNIQUE (marketing_id, position),
    CONSTRAINT fk_marketing_media_marketing FOREIGN KEY (marketing_id) REFERENCES marketing_contents (id) ON DELETE CASCADE,
    CONSTRAINT fk_marketing_media_media FOREIGN KEY (media_id) REFERENCES media_files (id) ON DELETE RESTRICT
);

CREATE TABLE instagram_integrations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    store_id BIGINT NOT NULL,
    instagram_user_id VARCHAR(100) NOT NULL,
    username VARCHAR(100) NOT NULL,
    access_token_encrypted TEXT NOT NULL,
    token_expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
    connected_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_instagram_integrations_store FOREIGN KEY (store_id) REFERENCES stores (id) ON DELETE CASCADE,
    CONSTRAINT uq_instagram_integrations_store UNIQUE (store_id)
);

CREATE INDEX idx_instagram_integrations_expiry
    ON instagram_integrations (token_expires_at);

CREATE TABLE instagram_oauth_states (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    state_hash VARCHAR(64) NOT NULL,
    store_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
    used_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uq_instagram_oauth_state_hash UNIQUE (state_hash),
    CONSTRAINT fk_instagram_oauth_states_store FOREIGN KEY (store_id) REFERENCES stores (id) ON DELETE CASCADE,
    CONSTRAINT fk_instagram_oauth_states_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE INDEX idx_instagram_oauth_states_expiry
    ON instagram_oauth_states (expires_at);
