SET TIME ZONE 'Asia/Seoul';

ALTER TABLE users ALTER COLUMN created_at SET DATA TYPE TIMESTAMP;
ALTER TABLE users ALTER COLUMN updated_at SET DATA TYPE TIMESTAMP;

ALTER TABLE stores ALTER COLUMN created_at SET DATA TYPE TIMESTAMP;
ALTER TABLE stores ALTER COLUMN updated_at SET DATA TYPE TIMESTAMP;
ALTER TABLE stores DROP COLUMN time_zone;

ALTER TABLE products ALTER COLUMN created_at SET DATA TYPE TIMESTAMP;
ALTER TABLE products ALTER COLUMN updated_at SET DATA TYPE TIMESTAMP;

ALTER TABLE sale_transactions ALTER COLUMN sold_at SET DATA TYPE TIMESTAMP;
ALTER TABLE sale_transactions ALTER COLUMN cancelled_at SET DATA TYPE TIMESTAMP;
ALTER TABLE sale_transactions ALTER COLUMN created_at SET DATA TYPE TIMESTAMP;

ALTER TABLE consultings ALTER COLUMN next_retry_at SET DATA TYPE TIMESTAMP;
ALTER TABLE consultings ALTER COLUMN generated_at SET DATA TYPE TIMESTAMP;
ALTER TABLE consultings ALTER COLUMN created_at SET DATA TYPE TIMESTAMP;
ALTER TABLE consultings ALTER COLUMN updated_at SET DATA TYPE TIMESTAMP;

ALTER TABLE chat_rooms ALTER COLUMN created_at SET DATA TYPE TIMESTAMP;
ALTER TABLE chat_rooms ALTER COLUMN updated_at SET DATA TYPE TIMESTAMP;

ALTER TABLE chat_messages ALTER COLUMN next_retry_at SET DATA TYPE TIMESTAMP;
ALTER TABLE chat_messages ALTER COLUMN created_at SET DATA TYPE TIMESTAMP;
ALTER TABLE chat_messages ALTER COLUMN updated_at SET DATA TYPE TIMESTAMP;

ALTER TABLE media_files ALTER COLUMN created_at SET DATA TYPE TIMESTAMP;

ALTER TABLE marketing_contents ALTER COLUMN next_publish_at SET DATA TYPE TIMESTAMP;
ALTER TABLE marketing_contents ALTER COLUMN approved_at SET DATA TYPE TIMESTAMP;
ALTER TABLE marketing_contents ALTER COLUMN published_at SET DATA TYPE TIMESTAMP;
ALTER TABLE marketing_contents ALTER COLUMN created_at SET DATA TYPE TIMESTAMP;
ALTER TABLE marketing_contents ALTER COLUMN updated_at SET DATA TYPE TIMESTAMP;

ALTER TABLE instagram_integrations ALTER COLUMN token_expires_at SET DATA TYPE TIMESTAMP;
ALTER TABLE instagram_integrations ALTER COLUMN connected_at SET DATA TYPE TIMESTAMP;
ALTER TABLE instagram_integrations ALTER COLUMN created_at SET DATA TYPE TIMESTAMP;
ALTER TABLE instagram_integrations ALTER COLUMN updated_at SET DATA TYPE TIMESTAMP;

ALTER TABLE instagram_oauth_states ALTER COLUMN expires_at SET DATA TYPE TIMESTAMP;
ALTER TABLE instagram_oauth_states ALTER COLUMN used_at SET DATA TYPE TIMESTAMP;
ALTER TABLE instagram_oauth_states ALTER COLUMN created_at SET DATA TYPE TIMESTAMP;
