DROP TABLE IF EXISTS instagram_oauth_states;
DROP TABLE IF EXISTS instagram_integrations;

CREATE TABLE instagram_accounts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    store_id BIGINT NOT NULL,
    account_id VARCHAR(100) NOT NULL,
    password_plaintext VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_instagram_accounts_store FOREIGN KEY (store_id) REFERENCES stores (id) ON DELETE CASCADE,
    CONSTRAINT uq_instagram_accounts_store UNIQUE (store_id)
);
